module.exports = [
    {
        id: 1,
        user_id: 2,
        google_places_id: 'ChIJheYkn7NzhlQR8weTw-mG_IU',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        user_id: 2,
        google_places_id: 'ChIJD8oBSnBxhlQRaX3X1supJ0g',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        user_id: 2,
        google_places_id: 'ChIJJ_oZQcpzhlQRYmMyGpKp7PA',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        user_id: 2,
        google_places_id: 'ChIJS7QNEQd0hlQRuTZ2xFQRWHk',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        user_id: 2,
        google_places_id: 'ChIJOU68-ztzhlQRg30p3Cl_XoI',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        user_id: 2,
        google_places_id: 'ChIJJzFAF9VzhlQRENeLwMlDVl8',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        user_id: 2,
        google_places_id: 'ChIJ-VlvsPdzhlQRVkrLK5hQOpQ',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        user_id: 2,
        google_places_id: 'ChIJpZ9V1xd4hlQRiYMPDgrA8fY',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        user_id: 2,
        google_places_id: 'ChIJSdeB41B3hlQRz4KYQtNHDE4',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        user_id: 2,
        google_places_id: 'ChIJe-XLV3FxhlQRp_RhBdLadTM',
        rating: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    
];