module.exports = [
    {
        id: 1,
        user_id: 1,
        google_places_id: 'ChIJWVntFo52hlQRD09-SMxntUk',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        user_id: 2,
        google_places_id: 'ChIJWVntFo52hlQRD09-SMxntUk',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        user_id: 3,
        google_places_id: 'ChIJWVntFo52hlQRD09-SMxntUk',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        user_id: 1,
        google_places_id: 'ChIJu1r9tIFxhlQRsfy5cILqdDs',
        rating: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 5,
        user_id: 2,
        google_places_id: 'ChIJu1r9tIFxhlQRsfy5cILqdDs',
        rating: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 6,
        user_id: 3,
        google_places_id: 'ChIJu1r9tIFxhlQRsfy5cILqdDs',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 7,
        user_id: 1,
        google_places_id: 'ChIJlyu4u4NxhlQRkUpN_iFwl8Q',
        rating: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 8,
        user_id: 1,
        google_places_id: 'ChIJ01q5UlVyhlQR7pkkpLz3Pkg',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 9,
        user_id: 1,
        google_places_id: 'ChIJC5sQuwJ1hlQRLnEuCNKPHpM',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 10,
        user_id: 1,
        google_places_id: 'ChIJzW_bVcoKhlQRjkyY9Fh1ysQ',
        rating: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    
];